name: aoc2018
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies: { charcode: ^1.3.1, dart_console: ^1.0.0, image: ^3.2.0, stack: ^0.2.1, tuple: ^2.0.0 }
dev_dependencies: { lints: ^2.0.0 }
include: package:lints/recommended.yaml
